### ISSUE TITLE
How to completely remove an added agent node, including from the PE web interface?

### ISSUE THREAD

**Issue by lc12345670** [kinners00/puppet-enterprise-guide#5]
I want to completely remove old agent nodes from both the web interface and the server side.

**Comment by lc12345670** [comment]
![1692696437124](https://github.com/kinners00/puppet-enterprise-guide/assets/57556792/c8ff4488-cdf0-46ea-a74b-af7ec61f66e8)

**Comment by kinners00** [comment]
Hi there,

If you want to remove an agent node from management and therefore remove it from the Puppet GUI, you should first uninstall the Puppet agent directly on your target nodes by following these steps > [Uninstall Agents](https://www.puppet.com/docs/pe/2023.2/uninstalling#uninstall_agents)

This will remove the Puppet agent software but it will _not_ revoke the nodes certificate and remove the node from the Puppet Enterprise console.

To do this ^ you should SSH to the Primary server (formally master) and run: 

`puppet node purge <YOUR-NODES-CERTNAME>`

Of course you should substitute `<YOUR-NODES-CERTNAME>` with the actual certname of your node, as shown in the Puppet GUI. In your specific case this would look like the following:

`puppet node purge 154-31-33-216`

`puppet node purge 154.31.33.216`

Afterwards, you will need finish up by running the following on the Primary server:

`puppet agent -t`

Now when you refresh the node inventory page in the Puppet GUI, you should see that they have been successfully removed.

Best,
Marc
